export default function getRefs() {
  return {
    inputSearchForm: document.querySelector('.js-search-form'),
    eventList: document.querySelector('.js-event-list'),
    dropList: document.querySelector('.js-dropdown'),
    pagination: document.querySelector('.tui-pagination'),
    countryListDouble: document.querySelector('.country-list'),
    selectCountryBtn: document.getElementById('select-country-btn'),
    buttonScrollUp: document.querySelector('.button-scroll-up'),
    searchingBlock: document.querySelector('.searching-block'),
    switchTogle: document.querySelector('#theme-switch-toggle'),
    bodyTheme: document.querySelector('body'),
    openModalBtn: document.querySelector('.list'),
    closeModalBtn: document.querySelector('[data-modal-close]'),
    modal: document.querySelector('[data-modal]'),
    lightBoxOverlay: document.querySelector('.backdrop'),
    cardMurkup: document.querySelector('.modal-form'),
    moreBtn: document.querySelector('.btn-more'),
    locateModalBackdrop: document.querySelector('.js-location-backdrop'),
    openTeamModal: document.querySelector('.team-modal'),
    closeTeamModal: document.querySelector('.prefix-close'),
    elModal: document.querySelector('#Modal'),
    regBackdrop: document.querySelector('.js-reg-backdrop'),
    openLogin: document.querySelector('.login-button'),
    closeRegistration: document.querySelector('.js-close-reg'),
    form: document.getElementById('form'),
    button: document.getElementById('button-submit'),
    buttonAuth: document.querySelector('.login-icon'),
    buttonOut: document.querySelector('.home-icon'),
    inputLogin: document.getElementById('login'),
    inputPassword: document.getElementById('password'),
  };
}
