import './sass/main.scss';
import './js/searchEvent';
import './js/modal';
import './js/preloader';
import './js/buttonScrollUp';
import './js/locationModal';
import './js/team';
import './js/registerModal';
import './js/auth';
